# Generated by Django 5.0 on 2026-01-09 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='matchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('entryFee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gridSize', models.IntegerField()),
                ('speed', models.CharField(choices=[('SLOW', 'SLOW'), ('MEDIUM', 'MEDIUM'), ('FAST', 'FAST'), ('EXTREME', 'EXTREME')], max_length=16)),
                ('playersRequired', models.IntegerField()),
                ('maxPlayers', models.IntegerField()),
                ('livesPerPlayer', models.IntegerField(default=0)),
                ('wallSpawnInterval', models.IntegerField(default=5)),
                ('allowExtraLives', models.BooleanField(default=False)),
                ('maxExtraLives', models.IntegerField(default=2)),
                ('extraLifeCost', models.DecimalField(decimal_places=2, default=5, max_digits=12)),
                ('isActive', models.BooleanField(default=True)),
                ('displayOrder', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['displayOrder', 'name'],
            },
        ),
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'WAITING'), ('STARTING', 'STARTING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], max_length=16)),
                ('gridSize', models.IntegerField()),
                ('speed', models.CharField(max_length=16)),
                ('currentPlayers', models.IntegerField(default=0)),
                ('playersRequired', models.IntegerField()),
                ('totalPot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('startedAt', models.DateTimeField(blank=True, null=True)),
                ('completedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('isSoloMode', models.BooleanField(default=False)),
                ('forceStartedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forcedMatches', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchesWon', to=settings.AUTH_USER_MODEL)),
                ('matchType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matches.matchtype')),
            ],
        ),
        migrations.CreateModel(
            name='gameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickNumber', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('playerPositions', models.JSONField()),
                ('walls', models.JSONField()),
                ('countdownWalls', models.JSONField()),
                ('activePlayers', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameStates', to='matches.match')),
            ],
            options={
                'ordering': ['tickNumber'],
            },
        ),
        migrations.CreateModel(
            name='soloRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallsSurvived', models.IntegerField(default=0)),
                ('wallsHit', models.IntegerField(default=0)),
                ('coinsEarned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('coinsLost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('netCoins', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('survivalTime', models.IntegerField()),
                ('finalGridState', models.JSONField(blank=True, null=True)),
                ('startedAt', models.DateTimeField(auto_now_add=True)),
                ('endedAt', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soloRuns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='matchParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryFeePaid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('extraLivesPurchased', models.IntegerField(default=0)),
                ('livesRemaining', models.IntegerField(default=0)),
                ('placement', models.IntegerField(blank=True, null=True)),
                ('wallsHit', models.IntegerField(default=0)),
                ('botsEliminated', models.IntegerField(default=0)),
                ('survivalTime', models.IntegerField(blank=True, null=True)),
                ('coinReward', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('joinedAt', models.DateTimeField(auto_now_add=True)),
                ('eliminatedAt', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchParticipations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
    ]
