# Generated by Django 5.0 on 2026-01-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchparticipation',
            name='extraLivesPurchased',
        ),
        migrations.RemoveField(
            model_name='matchparticipation',
            name='livesRemaining',
        ),
        migrations.RemoveField(
            model_name='matchtype',
            name='allowExtraLives',
        ),
        migrations.RemoveField(
            model_name='matchtype',
            name='extraLifeCost',
        ),
        migrations.RemoveField(
            model_name='matchtype',
            name='livesPerPlayer',
        ),
        migrations.RemoveField(
            model_name='matchtype',
            name='maxExtraLives',
        ),
    ]
