# Generated by Django 5.0 on 2026-01-13 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_remove_matchparticipation_extralivespurchased_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressiveRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('botsEliminated', models.IntegerField(default=0)),
                ('won', models.BooleanField(default=False)),
                ('survivalTime', models.IntegerField()),
                ('coinsSpent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('coinsEarned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('finalGridState', models.JSONField(blank=True, null=True)),
                ('startedAt', models.DateTimeField(auto_now_add=True)),
                ('endedAt', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressiveRuns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
