# Generated by Django 5.0 on 2026-01-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_progressiverun'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchparticipation',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matchparticipation',
            name='replayData',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressiverun',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='progressiverun',
            name='replayData',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solorun',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='solorun',
            name='replayData',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
