# Generated by Django 5.0 on 2026-01-13 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_progressivehighestlevel'),
        ('matches', '0004_matchparticipation_ispublic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplayView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay_type', models.CharField(max_length=16)),
                ('replay_id', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replayViews', to='accounts.profile')),
            ],
            options={
                'unique_together': {('user', 'replay_type', 'replay_id')},
            },
        ),
    ]
