# Generated by Django 5.0 on 2026-01-14 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_replayview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchparticipation',
            name='isBot',
            field=models.BooleanField(default=False, help_text='Is this a bot player'),
        ),
        migrations.AddField(
            model_name='matchparticipation',
            name='username',
            field=models.CharField(blank=True, help_text='Username for bot players', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matchtype',
            name='hasBot',
            field=models.BooleanField(default=True, help_text='Automatically add 1 bot to the lobby'),
        ),
        migrations.AlterField(
            model_name='matchparticipation',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchParticipations', to=settings.AUTH_USER_MODEL),
        ),
    ]
