# Generated by Django 5.0 on 2026-01-14 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_matchparticipation_isbot_matchparticipation_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchparticipation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='matchparticipation',
            constraint=models.UniqueConstraint(condition=models.Q(('player__isnull', False)), fields=('match', 'player'), name='unique_real_player_per_match'),
        ),
    ]
