# Generated by Django 5.0 on 2026-01-14 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_alter_matchparticipation_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('WAITING', 'WAITING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('EXPIRED', 'EXPIRED')], max_length=16)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('expiresAt', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdPrivateLobbies', to=settings.AUTH_USER_MODEL)),
                ('match', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privateLobby', to='matches.match')),
                ('matchType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='privateLobbies', to='matches.matchtype')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='PrivateLobbyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joinedAt', models.DateTimeField(auto_now_add=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='matches.privatelobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privateLobbyMemberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('lobby', 'user')},
            },
        ),
    ]
