# Generated by Django 5.0 on 2026-01-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directmessage',
            options={'ordering': ['createdAt']},
        ),
        migrations.AlterModelOptions(
            name='globalchatmessage',
            options={'ordering': ['createdAt']},
        ),
    ]
