# Generated by Django 5.0 on 2026-01-09 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='botSkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('previewImage', models.ImageField(upload_to='skins/previews/')),
                ('colorPrimary', models.CharField(max_length=7)),
                ('colorSecondary', models.CharField(blank=True, max_length=7, null=True)),
                ('trailEffect', models.CharField(blank=True, choices=[('NONE', 'NONE'), ('GLOW', 'GLOW'), ('SPARKLE', 'SPARKLE'), ('FIRE', 'FIRE'), ('ICE', 'ICE')], max_length=16, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('isDefault', models.BooleanField(default=False)),
                ('rarity', models.CharField(choices=[('COMMON', 'COMMON'), ('RARE', 'RARE'), ('EPIC', 'EPIC'), ('LEGENDARY', 'LEGENDARY')], max_length=16)),
                ('displayOrder', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bot Skin',
                'verbose_name_plural': 'Bot Skins',
                'ordering': ['displayOrder', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ownedSkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchasedAt', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownedSkins', to=settings.AUTH_USER_MODEL)),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='cosmetics.botskin')),
            ],
            options={
                'verbose_name': 'Owned Skin',
                'verbose_name_plural': 'Owned Skins',
                'unique_together': {('player', 'skin')},
            },
        ),
    ]
