# Generated by Django 5.0 on 2026-01-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botskin',
            name='previewImage',
            field=models.ImageField(blank=True, null=True, upload_to='skins/previews/'),
        ),
    ]
