# Generated by Django 5.0 on 2026-01-09 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0002_alter_botskin_previewimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botskin',
            name='trailEffect',
        ),
    ]
