# Generated by Django 5.0 on 2026-01-09 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0003_remove_botskin_traileffect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botskin',
            name='colorPrimary',
        ),
        migrations.RemoveField(
            model_name='botskin',
            name='colorSecondary',
        ),
    ]
