# Generated by Django 5.0 on 2026-01-09 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('coins', models.DecimalField(decimal_places=2, default=100, max_digits=12)),
                ('soloHighScore', models.IntegerField(default=0)),
                ('totalWins', models.IntegerField(default=0)),
                ('totalMatches', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=True)),
                ('activityLog', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
