# Generated by Django 5.0 on 2026-01-12 06:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hasChangedPassword',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='isAnonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastActivityAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
