# Generated by Django 5.0 on 2026-01-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_haschangedpassword_profile_isanonymous_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isAnonymous',
        ),
    ]
