# Generated by Django 5.0 on 2026-01-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_isanonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='progressiveHighestLevel',
            field=models.IntegerField(default=0),
        ),
    ]
