# Generated by Django 5.0 on 2026-01-09 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cosmetics', '0001_initial'),
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='coinPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('coins', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('displayOrder', models.IntegerField(default=0)),
                ('iconImage', models.ImageField(blank=True, null=True, upload_to='shop/icons/')),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['displayOrder', 'name'],
            },
        ),
        migrations.CreateModel(
            name='coinPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripePaymentIntentId', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('REFUNDED', 'REFUNDED')], max_length=16)),
                ('coinAmount', models.IntegerField()),
                ('pricePaid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('completedAt', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='shop.coinpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coinPurchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transactionType', models.CharField(choices=[('PURCHASE', 'PURCHASE'), ('MATCH_ENTRY', 'MATCH_ENTRY'), ('MATCH_WIN', 'MATCH_WIN'), ('SKIN_PURCHASE', 'SKIN_PURCHASE'), ('SOLO_REWARD', 'SOLO_REWARD'), ('SOLO_PENALTY', 'SOLO_PENALTY'), ('EXTRA_LIFE', 'EXTRA_LIFE'), ('REFUND', 'REFUND')], max_length=16)),
                ('description', models.CharField(max_length=255)),
                ('balanceBefore', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balanceAfter', models.DecimalField(decimal_places=2, max_digits=12)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('relatedMatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='matches.match')),
                ('relatedSkin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cosmetics.botskin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
