# Generated by Django 5.0 on 2026-01-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settingKey', models.CharField(max_length=100, unique=True)),
                ('settingValue', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionType',
            field=models.CharField(choices=[('PURCHASE', 'PURCHASE'), ('MATCH_ENTRY', 'MATCH_ENTRY'), ('MATCH_WIN', 'MATCH_WIN'), ('SOLO_REWARD', 'SOLO_REWARD'), ('SOLO_PENALTY', 'SOLO_PENALTY'), ('EXTRA_LIFE', 'EXTRA_LIFE'), ('REFUND', 'REFUND'), ('USERNAME_CHANGE', 'USERNAME_CHANGE')], max_length=16),
        ),
    ]
