# Generated by Django 5.0 on 2026-01-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_add_default_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionType',
            field=models.CharField(choices=[('PURCHASE', 'PURCHASE'), ('MATCH_ENTRY', 'MATCH_ENTRY'), ('MATCH_WIN', 'MATCH_WIN'), ('SOLO_REWARD', 'SOLO_REWARD'), ('SOLO_PENALTY', 'SOLO_PENALTY'), ('PROGRESSIVE_ENTRY', 'PROGRESSIVE_ENTRY'), ('PROGRESSIVE_REWARD', 'PROGRESSIVE_REWARD'), ('EXTRA_LIFE', 'EXTRA_LIFE'), ('REFUND', 'REFUND'), ('USERNAME_CHANGE', 'USERNAME_CHANGE'), ('REPLAY_VIEW', 'REPLAY_VIEW')], max_length=20),
        ),
    ]
